name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      run: mvn -DskipTests package --file pom.xml
      
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      run: mvn test --file pom.xml
      

  sonarCloudTrigger:
    runs-on: ubuntu-latest
    name: SonarCloud Scan
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -Dmaven.test.failure.ignore=true test --file pom.xml 
        & mvn sonar:sonar -Dsonar.junit.reportPaths='target/surefire-reports' -Dsonar.organization=marci4-github -Dsonar.host.url=https://sonarcloud.io --file pom.xml
