name: Continuous Integration

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [8, 11, 17,21]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
      - name: Build JDK ${{ matrix.version }}
        run: mvn -DskipTests package --file pom.xml

  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        version: [8, 11, 17,21]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
      - name: Test JDK ${{ matrix.version }}
        run: mvn test --file pom.xml
